; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = mega_transmitter

[env]
platform = atmelavr
framework = arduino
lib_deps =
    nrf24/RF24@^1.6.0
    adafruit/Adafruit INA219@^1.2.3

# Transmitter setup on the Mega
[env:mega_transmitter]
board = megaatmega2560
src_filter = +<*> -<main.cpp> -<receiver.cpp>

# Receiver setup on the Uno
[env:uno_receiver]
board = uno
src_filter = +<*> -<main.cpp> -<transmitter.cpp>

# Standard Main application on the Mega
[env:mega_main]
board = megaatmega2560
src_filter = +<*> -<transmitter.cpp> -<receiver.cpp>

